name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install musl-tools
      run: sudo apt-get install -y musl-tools

    - name: Add musl target
      run: rustup target add x86_64-unknown-linux-musl

    - name: Build
      run: cargo build --release --target x86_64-unknown-linux-musl

    - name: Run tests
      run: cargo test --release --target x86_64-unknown-linux-musl

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: calibre-api
        path: |
          target/x86_64-unknown-linux-musl/release/calibre-api*
          !target/x86_64-unknown-linux-musl/release/calibre-api.d
        if-no-files-found: error